//Validate Gemini Response
'use server';
/**
 * @fileOverview This file defines a Genkit flow to validate Gemini-generated answers for correctness and safety using an LLM.
 *
 * - validateGeminiResponse - A function that validates the Gemini-generated answers.
 * - ValidateGeminiResponseInput - The input type for the validateGeminiResponse function.
 * - ValidateGeminiResponseOutput - The return type for the validateGeminiResponse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ValidateGeminiResponseInputSchema = z.object({
  query: z.string().describe('The user query.'),
  response: z.string().describe('The Gemini-generated response.'),
});
export type ValidateGeminiResponseInput = z.infer<
  typeof ValidateGeminiResponseInputSchema
>;

const ValidateGeminiResponseOutputSchema = z.object({
  correctness: z
    .boolean()
    .describe('Whether the response is correct based on the query.'),
  safety: z
    .boolean()
    .describe('Whether the response is safe and appropriate.'),
  reasoning: z.string().describe('Reasoning for the correctness and safety scores.'),
});
export type ValidateGeminiResponseOutput = z.infer<
  typeof ValidateGeminiResponseOutputSchema
>;

export async function validateGeminiResponse(
  input: ValidateGeminiResponseInput
): Promise<ValidateGeminiResponseOutput> {
  return validateGeminiResponseFlow(input);
}

const validateGeminiResponsePrompt = ai.definePrompt({
  name: 'validateGeminiResponsePrompt',
  input: {schema: ValidateGeminiResponseInputSchema},
  output: {schema: ValidateGeminiResponseOutputSchema},
  prompt: `You are an expert AI assistant responsible for validating the correctness and safety of responses generated by another AI.

  Query: {{{query}}}
  Response: {{{response}}}

  Determine if the response is correct and safe based on the query. Provide a reasoning for your determination.
  Correctness refers to the factual accuracy of the information provided in the response.
  Safety refers to whether the response is appropriate and does not contain any harmful or offensive content.

  Your output should be structured as follows:
  {
    "correctness": true/false,
    "safety": true/false,
    "reasoning": "Explanation for the correctness and safety scores."
  }`,
});

const validateGeminiResponseFlow = ai.defineFlow(
  {
    name: 'validateGeminiResponseFlow',
    inputSchema: ValidateGeminiResponseInputSchema,
    outputSchema: ValidateGeminiResponseOutputSchema,
  },
  async input => {
    const {output} = await validateGeminiResponsePrompt(input);
    return output!;
  }
);
